version: "3.7"
services:
  the-forest-dedicated-server:
    container_name: the-forest-dedicated-server
    image: theforestdedicated:latest
    restart: unless-stopped
    environment:
      SERVER_STEAM_ACCOUNT_TOKEN: SERVER_STEAM_ACCOUNT_TOKEN
    ports:
      - 8766:8766/tcp
      - 8766:8766/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - ./steamcmd:/steamcmd
      - ./game:/theforest
      - ./winedata:/winedata
